name: 'Saplings - Content types'
description: 'Configuration for the Saplings Content types.'
type: 'Site'
recipes:
  - saplings-content-base
  - saplings-component-types
install:
  # Core.
  - menu_ui
  # Contrib.
  - access_unpublished
  - field_group
  - metatag_open_graph
  - metatag_twitter_cards
  - pathauto
  - publication_date
  - scheduler
  - scheduler_content_moderation_integration
  - schema_article
  - simple_sitemap
  - token_or
  - ui_patterns_layouts
config:
  import:
    # Core.
    # Comment out as it is in saplings-base which we assume will be used.
    # Once #3390916 is merged in, we can uncomment this as we could import
    # config again if it is the same.
    # menu_ui: "*"
    # Contrib.
    access_unpublished: "*"
    scheduler:
      - scheduler.settings
      - views.view.scheduler_scheduled_content
  actions:
    # Set Metatag Home page:
    metatag.metatag_defaults.front:
      simple_config_update:
        canonical_url: '[site:url]'
        description: '[node:sa_description|node:sa_seo_description]'
        image_src: '[node:sa_featured_image:entity:field_media_image:sa_social_media_facebook]'
        og_description: '[node:sa_description|node:sa_seo_description]'
        og_image: '[node:sa_featured_image:entity:field_media_image:sa_social_media_facebook]'
        og_image_alt: '[node:sa_featured_image:entity:field_media_image:alt]'
        og_image_height: '[node:sa_featured_image:entity:field_media_image:sa_social_media_facebook:height]'
        og_image_type: '[node:sa_featured_image:entity:field_media_image:sa_social_media_facebook:mimetype]'
        og_image_width: '[node:sa_featured_image:entity:field_media_image:sa_social_media_facebook:width]'
        og_locale: en_US
        og_site_name: '[site:name]'
        og_title: '[node:sa_seo_page_title|node:title]'
        og_type: website
        og_updated_time: '[node:changed:custom:c]'
        og_url: '[current-page:url:absolute]'
        referrer: unsafe-url
        rights: 'Copyright ©[date:html_year] All rights reserved.'
        shortlink: '[site:url]'
        title: '[node:sa_seo_page_title|node:title] | [site:name]'
        twitter_cards_description: '[node:sa_description|node:sa_seo_description]'
        twitter_cards_image: '[node:sa_featured_image:entity:field_media_image:sa_social_media_x:url]'
        twitter_cards_image_alt: '[node:sa_featured_image:entity:field_media_image:alt]'
        twitter_cards_title: '[node:sa_seo_page_title|node:title]'
        twitter_cards_type: summary_large_image
    # @TODO: Set permissions for content editor role.
