name: 'Saplings - Content types'
description: 'Configuration for the Saplings Content types.'
type: 'Site'
recipes:
  - saplings-content-base
  - saplings-component-types
install:
  # Core.
  - menu_ui
  # Contrib.
  - access_unpublished
  - entity_browser
  - entity_browser_entity_form
  - field_group
  - inline_entity_form
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - pathauto
  - publication_date
  - scheduler
  - scheduler_content_moderation_integration
  - schema_article
  - schema_metatag
  - simple_sitemap
  - token_or
  - tour
  - ui_patterns_layouts
config:
  import:
    # Contrib.
    metatag: "*"
    pathauto: "*"
    scheduler:
      - views.view.scheduler_scheduled_content
    schema_metatag: "*"
  actions:
    # Set Metatag Home page:
    metatag.metatag_defaults.front:
      simple_config_update:
        tags.canonical_url: '[site:url]'
        tags.description: '[node:sa_description|node:sa_seo_description]'
        tags.image_src: '[node:sa_seo_image:entity:field_media_image:sa_social_media_facebook|node:sa_featured_image:entity:field_media_image:sa_social_media_facebook]'
        tags.og_description: '[node:sa_description|node:sa_seo_description]'
        tags.og_image: '[node:sa_seo_image:entity:field_media_image:sa_social_media_facebook|node:sa_featured_image:entity:field_media_image:sa_social_media_facebook]'
        tags.og_image_alt: '[node:sa_seo_image:entity:field_media_image:alt|node:sa_featured_image:entity:field_media_image:alt]'
        tags.og_image_height: '[node:sa_seo_image:entity:field_media_image:sa_social_media_facebook:height|node:sa_featured_image:entity:field_media_image:sa_social_media_facebook:height]'
        tags.og_image_type: '[node:sa_seo_image:entity:field_media_image:sa_social_media_facebook:mimetype|node:sa_featured_image:entity:field_media_image:sa_social_media_facebook:mimetype]'
        tags.og_image_width: '[node:sa_seo_image:entity:field_media_image:sa_social_media_facebook:width|node:sa_featured_image:entity:field_media_image:sa_social_media_facebook:width]'
        tags.og_locale: en_US
        tags.og_site_name: '[site:name]'
        tags.og_title: '[node:sa_seo_page_title|node:title]'
        tags.og_type: website
        tags.og_updated_time: '[node:changed:custom:c]'
        tags.og_url: '[current-page:url:absolute]'
        tags.referrer: unsafe-url
        tags.rights: 'Copyright ©[date:html_year] All rights reserved.'
        tags.shortlink: '[site:url]'
        tags.title: '[node:sa_seo_page_title|node:title] | [site:name]'
        tags.twitter_cards_description: '[node:sa_description|node:sa_seo_description]'
        tags.twitter_cards_image: '[node:sa_seo_image:entity:field_media_image:sa_social_media_x:url|node:sa_featured_image:entity:field_media_image:sa_social_media_x:url]'
        tags.twitter_cards_image_alt: '[node:sa_seo_image:entity:field_media_image:alt|node:sa_featured_image:entity:field_media_image:alt]'
        tags.twitter_cards_title: '[node:sa_seo_page_title|node:title]'
        tags.twitter_cards_type: summary_large_image
    # Set permissions for anonymous role.
    user.role.anonymous:
      ensure_exists:
        id: anonymous
      grantPermissions:
        - 'access content'
        - 'access sitemap'
        - 'access_unpublished node sa_page'
        - 'access_unpublished node sa_post'
    # Set permissions for content editor role.
    user.role.content_editor:
      ensure_exists:
        id: content_editor
      grantPermissions:
        - 'access administration pages'
        - 'access block library'
        - 'access content overview'
        - 'access environment indicator'
        - 'access environment indicator ribbon'
        - 'access help pages'
        - 'access media overview'
        - 'access patterns page'
        - 'access shortcuts'
        - 'access site in maintenance mode'
        - 'access sitemap'
        - 'access taxonomy overview'
        - 'access toolbar'
        - 'access tour'
        - 'access_unpublished node sa_page'
        - 'access_unpublished node sa_post'
        - 'administer menu'
        - 'administer redirects'
        - 'change own username'
        - 'clone sa_page content'
        - 'clone sa_post content'
        - 'create media'
        - 'create sa_page content'
        - 'create sa_post content'
        - 'create terms in sa_category'
        - 'create terms in sa_post_type'
        - 'create url aliases'
        - 'delete media'
        - 'delete own sa_page content'
        - 'delete own sa_post content'
        - 'delete sa_page revisions'
        - 'delete sa_post revisions'
        - 'edit any sa_page content'
        - 'edit any sa_post content'
        - 'edit own sa_page content'
        - 'edit own sa_post content'
        - 'edit terms in sa_category'
        - 'edit terms in sa_post_type'
        - 'ignore 404 requests'
        - 'renew token'
        - 'revert all revisions'
        - 'revert sa_page revisions'
        - 'revert sa_post revisions'
        - 'schedule publishing of media'
        - 'schedule publishing of nodes'
        - 'schedule publishing of taxonomy_term'
        - 'set sa_page published on date'
        - 'set sa_post published on date'
        - 'switch shortcut sets'
        - 'update any media'
        - 'update media'
        - 'use admin toolbar search'
        - 'use text format full_html'
        - 'view all media revisions'
        - 'view all revisions'
        - 'view any unpublished content'
        - 'view any unpublished sa_page content'
        - 'view any unpublished sa_post content'
        - 'view latest version'
        - 'view own unpublished content'
        - 'view own unpublished media'
        - 'view sa_page revisions'
        - 'view sa_post revisions'
        - 'view scheduled content'
        - 'view scheduled media'
        - 'view scheduled taxonomy_term'
        - 'view the administration theme'
        - 'view unpublished paragraphs'
